# Docker Configuration for Cubism SDK Web

docker:
  # Dockerfile name
  dockerfile: "volume/Dockerfile"

  # Docker image settings
  image:
    name: "img_node"
    version: "latest"

  # Docker container settings
  container:
    name: "node_server"
    port: "5000"

# Cubism SDK settings
cubism:
  # Git repository and tag for Cubism SDK
  sdk_git_repo: "https://github.com/Live2D/CubismWebSamples.git"
  sdk_git_tag: "5-r.4"

  # Path to Core archive directory
  archive_core_dir: "./volume/Core"
