# Docker container settings
docker_container_name: Haru

# Configuration for creating the Docker container
create:
  # [REQUIRED]
  # absolute or relative path to the workspace directory (where the REQUIRED files are located)
  workspace: ../

  # moc3 file for Cubism SDK Web
  moc3_file: archives/Resources/Haru/Haru.moc3
  # Archive file for Cubism SDK Web
  sdk_archive: archives/CubismSdkForWeb-5-r.5-beta.3.zip

  # Dockerfile name
  dockerfile: src/CubismContainer/volume/Dockerfile
  # target directory for custom code
  code_dir: src/adapter

  # [OPTIONAL]
  # Docker image settings
  docker_image_name: acting_doll_image

# Docker Configuration for Cubism SDK Web
settings:
  # Docker container ports
  port:
    http: 8080
    websocket: 8765
    mcp: 3001
  # Authentication settings for WebSocket connections
  authentication:
    token: your_authentication_token_here
  # Enable or disable outputting the configuration as YAML
  output_yaml: true

# Cubism SDK information
cubism:
  # Git repository and tag for Cubism Framework
  git_framework_dir_name: Framework
  git_framework_repo: https://github.com/Live2D/CubismWebFramework.git
  git_framework_tag: 5-r.5-beta.3

  # Git repository and tag for Cubism Web Samples
  git_sample_dir_name: Samples
  git_sample_repo: https://github.com/Live2D/CubismWebSamples.git
  git_sample_tag: 5-r.5-beta.3
