# Docker Configuration for Cubism SDK Web
docker:
  # Docker image settings
  image:
    name: "img_node"
    version: "latest"

  # Docker container settings
  container:
    name: "server_acting_doll"
    port_cubism: "5000"
    port_websocket: "8765"

  # Dockerfile name
  dockerfile: "volume/Dockerfile"

# Cubism SDK settings
cubism:
  # Git repository and tag for Cubism Framework
  git_framework_repo: "https://github.com/Live2D/CubismWebFramework.git"
  git_framework_tag: "5-r.4"
  git_framework_dir_name: "Framework"

  # Git repository and tag for Cubism Web Samples
  git_sample_repo: "https://github.com/Live2D/CubismWebSamples.git"
  git_sample_tag: "5-r.4"
  git_sample_dir_name: "Samples"

  # Path to Core archive directory
  archive_core_dir: "../../src/Cubism/Core"

# Custom code paths
custom:
  # Path to adapter directory
  adapter_dir: "../../src/adapter"
